server:
  port: 8002


spring:
  application:
    name: cloud-payment-service
  Zipkin:
    base-url: http://localhost:9411

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://49.234.66.35:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Lxy@123456
  devtools:
    add-properties: false
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  sleuth:
    sampler:
      #采集率介于0到1之间，1则表示全部采集
      probability: 1

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包


eureka:
  client:
    service-url:
       defaultZone: http://eureka7001.com:7002/eureka,http://eureka7002.com:7001/eureka
       #表示将自己注册进EurekaServer
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息
    fetch-registry: true
  instance:

    instance-id: payment8002
    #访问路径可以显示IP地址
    prefer-ip-address: true
      #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
      #lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    #lease-expiration-duration-in-seconds: 2
